### ISSUE TITLE
http proxy is not working using node 0.12.7

### ISSUE THREAD

**Issue by basetta** [librato/statsd-librato-backend#53]
Hi,
Unfortunately, updating the nodejs version, the librato backend is not working anymore.

More precisely, we are getting the following excpetion 

```
_http_client.js:73
    throw new TypeError('Request path contains unescaped characters.');
          ^
TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:73:11)
    at TunnelingAgent.exports.request (http.js:49:10)
    at TunnelingAgent.createSocket (/opt/statsd/node_modules/tunnel/lib/tunnel.js:116:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/opt/emarsys/statsd/node_modules/tunnel/lib/tunnel.js:188:41)
    at TunnelingAgent.addRequest (/opt/statsd/node_modules/tunnel/lib/tunnel.js:80:8)
    at new ClientRequest (_http_client.js:154:16)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at post_payload (/opt/statsd/node_modules/statsd-librato-backend/lib/librato.js:64:18)
    at post_metrics (/opt/statsd/node_modules/statsd-librato-backend/lib/librato.js:149:3)
```

As you can see is a problem in the tunnel library, I was wondering If it would make sense to use another library.

**Comment by mheffner** [comment]
@basetta Are you aware of any alternative tunneling libraries that work well and have Node.js 12 compatibility? I'm not bound to anyone library, but I don't do a lot of Node.js work nor use the tunneling support so I'd likely need some assistance on porting.

**Comment by basetta** [comment]
@mheffner yes I did a small pull-request https://github.com/librato/statsd-librato-backend/pull/54.

Please have a look. Keep in mind that I am not a node developer at all :D
